version: "3"

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: 'gio'
      POSTGRES_PASSWORD: 'testing123'
      POSTGRES_DB: 'my_db'
    ports:
      - 15432:5432
  prisma:
    depends_on:
      - db
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            database: my_db
            host: db
            port: 5432
            user: gio
            password: testing123
  server:
    depends_on:
      - prisma
    image: parlezvous/server
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:3000
