# This docker-compose file is exclusively for local development
# hence why we create a volume mapping between the "server" image files and 
# the files on your file system

version: "3"

services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: 'gio'
      POSTGRES_PASSWORD: 'testing123'
      POSTGRES_DB: 'my_db'
    ports:
      - 15432:5432
  server:
    image: parlezvous/server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:8080

