version: 2
jobs:
  build:
    branches:
      only:
        - master
        
    docker:
      - image: parlezvous/ci-base:0.3.0

    steps:
      - checkout

      # TODO: run tests + linting
      
      - run:
          name: "Deploy"
          # Generate app.yaml for GAE
          # logs into gcloud
          # deploys to GAE
          command: |
            python generate-app-yaml.py > app.yaml
            echo $GCLOUD_SERVICE_ACCOUNT_KEY_FILE | base64 --decode > key.json
            gcloud auth activate-service-account --key-file=./key.json --project=$GCLOUD_PROJECT_ID
            gcloud app deploy --quiet
