version: 2.1
jobs:
  build:
    machine:
      docker_layer_caching: true

    # export DATABASE_URL
    # npm run migrate:up

    steps:
      - checkout

      - run:
          name: NOOP
          command: echo "HELLO WORLD :)"
