version: 2
jobs:
  build:
    docker:
      - image: parlezvous/ci-base:0.3.0

    steps:
      - checkout

      # TODO: run tests + linting
      
      - run:
          name: "Generate config file"
          command: python generate-app-yaml.py > app.yaml

      #
      # TODO: log into gcloud
      #
      # - run:
      #     name: "Deploy"
      #     command: gcloud app deploy --quiet
