version: 2
jobs:
  build:
    docker:
      - image: parlezvous/ci-base:0.1.0

    # export DATABASE_URL
    # npm run migrate:up

    steps:
      - checkout

      - run:
          name: NOOP
          command: echo $DATABASE_NAME
